### ISSUE TITLE
About Accuracy

### ISSUE THREAD

**Issue by SunYanCN** [KhrulkovV/tt-pytorch#2]
I test this:
`python train.py --gpu=0 --embed_dim=256 --dataset=imdb --n_epochs=100`
![image](https://user-images.githubusercontent.com/42198591/53617399-014eb200-3c22-11e9-9c8d-cd5e4a937ebe.png)
Is there a problem with the formula for calculating the correct rate?

**Comment by KhrulkovV** [comment]
Thanks, there indeed was a small bug in accuracy computation. Fixed now, sorry for the late response.
